### ISSUE TITLE
Live preview doesn't work properly

### ISSUE THREAD

**Issue by Sraw** [JaxsonWang/WP-Editor.md#198]
There are several problems about live preview and editor.

1. `'` cannot be rendered properly in live preview. For example, `I'm` will be rendered as `I’m`.

2. It seems inserting a link which doesn't start with `http` will cause format error. For example, inserting a link like `[asdfasdf](example@gmail.com "asdfasdf")` will be rendered as `example@gmail.com" title="asdfasdf">asdfasdf`.

The above are two problems in live preview, they all work well in real page. So I think this is not an issue related to Jetpack.

And there is another issue related to editor itself. Link will be extended after update, for example `[asdfasdf](example@gmail.com "asdfasdf")` will be extended as `<a href="example@gmail.com" title="asdfasdf">asdfasdf</a>`. That causes difficulty to edit next time.

**Comment by JaxsonWang** [comment]
- `'`confirm the problem and the next version will fix it.
- I think your insert link format is not standardized because of the lack of a claim protocol type..e.g: `[asdfasdf](mailto:example@gmail.com "asdfasdf")` or `[mylink](//mylink.com)`. [more info](https://www.w3schools.com/tags/att_a_href.asp)

**Comment by Sraw** [comment]
Yes it lacks a protocol type but as I have said it works in real page.
And you can see, even github supports it well.
[asdfasdf](example@gmail.com "asdfasdf")

BTW, how about the extended expression?
